name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run unit tests
        run: |
          pip install --upgrade pip
          pip install poetry
          poetry update

          export PYTHONPATH=$(pwd)
          poetry run py.test --cov=love_letter --cov-report html tests
          poetry run behave
