name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run unit tests
        run: |
          ./tests/run-tests.sh

      - name: Run unit tests with real storage
        run: |
          export repository_impl=pickle
          ./tests/run-tests.sh

      - name: Run unit tests with mongo
        run: |
          export repository_impl=mongo
          ./tests/run-tests.sh
